# Generated by Django 3.2.4 on 2021-06-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_auto_20210603_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='picture',
            field=models.ImageField(null=True, upload_to='portfolios/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
